ANDROID_NAME = 'name_for_your_android'
ANDROID_IP = 'You.rIp.H.ere'
ADB_EXECUTABLE_PATH = r'c:\folder\where\adb\is\adb.exe'
ANDROID_MUSIC_FOLDER_PATH = '/path/of/music/folder/in/android/'
PC_MUSIC_FOLDER_PATH = r'c:\path\of\music\folder\in\pc'
